const COOKIES = {
    'chocolate-chip': {
        id: 'chocolate-chip',
        name: 'Chocolate Chip Cookie',
        image: '/cookies/1.png',
        price: '$20.00',
        stars: 4,
        description: 'Chocolate chip cookies are the perennial classic and longtime fan favorite. They can be soft and chewy or crispy and crunchy depending on how you make them and the ingredients you use. Either way, they’re completely delicious.',
    },
    'gingerbread': {
        id: 'gingerbread',
        name: 'Gingerbread Cookie',
        image: '/cookies/2.png',
        price: '$30.00',
        stars: 5,
        description: 'Gingerbread cookies are the ultimate holiday cookie. They’re made with spices galore, including cinnamon, ginger, nutmeg, and molasses, and are made by rolling out the dough and cutting into shapes.',
    },
    'shortbread': {
        id: 'shortbread',
        name: 'Shortbread Cookie',
        image: '/cookies/3.png',
        price: '$30.00',
        stars: 5,
        description: 'Shortbread cookies are made with a large amount of butter or shortening, which lends them the name “short.” Due to their low amount of flour and sugar, they have a classic crumbly and tender texture.',
    },
    'oatmeal-raisin': {
        id: 'oatmeal-raisin',
        name: 'Oatmeal Raisin Cookie',
        image: '/cookies/4.png',
        price: '$30.00',
        stars: 4,
        description: 'Oatmeal raisin is a type of drop cookie. as its name suggests, it’s made with oats, and contains raisins and brown sugar. They can be crispy and crunchy or chewy, depending on the ingredients you use and how long you bake them.',
    },
    'fortune': {
        id: 'fortune',
        name: 'Fortune Cookie',
        image: '/cookies/5.png',
        price: '$30.00',
        stars: 5,
        description: 'Fortune cookies are mostly known as the type of cookie that comes with Chinese takeout. They’re made with flour, sugar, vanilla, and just a hint of sesame oil and are shaped into their classic crescent shape while the dough is still hot from the oven.',
    },
    'macaroon': {
        id: 'macaroon',
        name: 'Macaroon',
        image: '/cookies/6.png',
        price: '$30.00',
        stars: 5,
        description: 'Macaroons are coconut based with a dense, lumpy texture that’s sweet and chewy. Some macaroons are even dipped in chocolate for extra indulgence.',
    },
    'biscotti': {
        id: 'biscotti',
        name: 'Biscotti',
        image: '/cookies/7.png',
        price: '$10.00',
        stars: 4,
        description: 'Biscotti actually means “twice baked” and the cookie is indeed baked twice, resulting in its hard and crunchy texture. Biscotti come in a wide array of flavors and toppings, from plain almond to double chocolate and so much more.',
    },
};

export default COOKIES;